### PR TITLE
HasRoleDirective and Refactoring

### PR DESCRIPTION
**Pull request by GNSSYSTEMS-tg**
* `HasRoleDirective` improved
* `AuthGuard`  renamed to `HasRoleGuard`
* `SimpleAuthGuard` renamed to `AuthGuard`
* moved guards and services into own directories

### CODE REVIEW

**Comment by GNSSYSTEMS-tg** [comment]
I'm fine with this, so feel free to merge :)

**Comment by IsNull** [comment]
Hey thanks for your contribution, the im happy to see the improved HasRole directive!

But I also noticed that you have renamed public API Members (the auth guards) which will break all existing code and thus I am hesitant of merging this. For now I would prefer that you rollback the renaming in this PR so that we can discuss it first and handle it in another PR separately. 

The renaming would have to be made in a way that does not break existing code, instead we would just mark some selectors as deprecated.

Btw, the moving of the services / guards in other directories is fine as it has no effect on the public API.

**Comment by GNSSYSTEMS-tg** [comment]
Mh, I was thinking of the public api aspect as well, but since configuration has already changed a lot and the version is going to be bumped to `2.0, I figured "what's the harm?" But alright, if you prefer to stick with previous names...

**Comment by IsNull** [comment]
You are right, especially because this is a beta version.

The problem is that at least we use the beta version internally in a number of projects already, so it would really break stuff for us, and I would like to avoid this for now. 😄  

But we can certainly discuss better names and come up with a migration.

**Comment by GNSSYSTEMS-tg** [comment]
* reverted renaming of `SimpleAuthGuard` (from `AuthGuard`)
* added deprecated `AuthGuard` as copy of `HasRoleGuard`

**Comment by GNSSYSTEMS-tg** [comment]
In my point of view `AuthGuard` should be called `HasRoleGuard` to be consistent with `HasRoleDirective`.

**Comment by GNSSYSTEMS-tg** [comment]
Ok, fine with me now.

**Comment by GNSSYSTEMS-tg** [comment]
Added inversions:
* added `HasNotRoleGuard` and `HasNotRoleDirective`
* added `HasNoRolesGuard` and `HasNoRolesDirective`
* adjusted `PrincipalService` and `AuthService` accordingly

**Pull request merged**
