### PR TITLE
Extension for AuthService API

### PR DESCRIPTION
**Pull request by GNSSYSTEMS-tg**

### CODE REVIEW

**Comment by GNSSYSTEMS-tg** [comment]
Ok, this was my last addition.

**Comment by IsNull** [comment]
Is there a special use-case which requires this?  Since the library will invoke this basically automatically before every route change if you are not logged in.

The params map may likely be empty, resulting in a cache login automatically if available.

**Comment by GNSSYSTEMS-tg** [comment]
True, but for some reason, starting with `/login` requires to login. It does not forward to the configured landing page.

**Comment by IsNull** [comment]
Well I guess this is because the library tries to be smart and redirect the user where it wanted to go.
I.e. if your user wants to visit `/customers` and was not logged in, he will be redirected to /customers after successful login. 
However, if your user explicitly wants to go to `/login`, he will be redirected to `/login` after successful login.

I guess we should solve the root of the problem. I'll have to go now, but will have a look at this later in the day.

**Comment by GNSSYSTEMS-tg** [comment]
But there is no log saying "Found JWT"....

**Comment by GNSSYSTEMS-tg** [comment]
Still, I've got the issue that opening `/login` first, an existing token is not detected. Apparently, NavigationStart is not triggered on the very first page. Thus I'm pleading for a public API for `tryAuthenticate`.

Another point: The Choice of refreshment strategy should be a DEBUG-Message, not INFO.

**Comment by IsNull** [comment]
>Still, I've got the issue that opening /login first, an existing token is not detected. Apparently, NavigationStart is not triggered on the very first page. Thus I'm pleading for a public API for tryAuthenticate.

This supports your case out of the box. Visiting any url of the web app and getting automatically logged in is a very basic use-case. And I tested it with several of our services and it seems to work.
At which point would you invoke try-authenticate? If necessary we can do this internally at startup.

Did you test this with any other route which is not login and is protected by a role guard so we can isolate the problem?

**Comment by GNSSYSTEMS-tg** [comment]
I tested it with various routes. But my routes use `SimpleAuthGuard`, so each is forwarded to `/login` and then `NavigationStart` is triggered.

If I start with `/login` though, `NavigationStart` is not triggered. Maybe newer angular versions don't support this anymore? My version is `4.3.2`.

Btw. I've added a configuration entry for "force reload" after login.

**Comment by IsNull** [comment]
>If I start with /login though, NavigationStart is not triggered. Maybe newer angular versions don't support this anymore? My version is 4.3.2.

I'm usually on the latest Angular version, so I doubt this is the reason. Anyway, that is quite strange. Due to HTML5 mode, the server is always also part of the equation here. (Just saying since it gave us trouble in the beginning as well)

I just saw your new config for the navigation url handling. This is something I want to address automatically. Before my change, it always used a local route, thus the OAuth redirect was obviously not working. Now it always uses the window.href for a redirect. While this works for local* and OAuth, a local redirect would be better. But the library should be smart enough to handle this correctly on its own (i.e. no additional config necessary).

*_local works because the token lands in the local/session storage and is available after reload._

I would prefer if we could discuss changes in a issue before you actually do them in a PR. This way we can discuss if its a feature, bug and how to support the use-case. Also, we can avoid doing duplicate work as we are both working on very similar things.

**Comment by GNSSYSTEMS-tg** [comment]
Yep, that's true. PR got pretty messy.

I'm working on an animation from login page to the rest. Reloading destroys this opportunity. I'll get back to you next month with this, since I'll be out of office for two weeks.

**Comment by IsNull** [comment]
I have changed the base to master. To counter the messiness - even if just for reference now.

>I'm working on an animation from login page to the rest. Reloading destroys this opportunity. I'll get back to you next month with this, since I'll be out of office for two weeks.

I will support local redirect without reloading. The reloading was just a dirty hack to fix OAuth and still allow local.  Sorry for breaking your animation. :)

**Pull request closed without merging**
