### PR TITLE
Support for Token Refresh

### PR DESCRIPTION
**Pull request by GNSSYSTEMS-tg**
Attention:

Changed Configuration due to inconsistent naming of options:
 
* `backendLoginApi` is now `obtainTokenUrl`.

I kept the original around, but marked it as deprecated. This attribute should be removed in the future and at the same time `obtainTokenUrl` made required.

As always: quick release is much appreciated!

### CODE REVIEW

**Comment by IsNull** [comment]
I will have a quick look and release it asap! Thank you for your contributions!

**Comment by IsNull** [comment]
I have made a short code review and while doing so, I have observed that the refresh-token flow you have implemented is not quite the standard. As far as I understand, the access_token and the refresh_token are two different things. The access_token is the signed JWT for stateless auth handling and should optimally be rather short lived. The refresh_token on the other hand can be opaque to the client, meaning it is just a random string token which can be used to fetch a new access_token.

If you think about it: You can not fetch a new JWT with an already expired JWT as by definition, an expired JWT has no (auth) value at all and wont be trusted.

I found the following links quite well written about refresh tokens:

https://auth0.com/learn/refresh-tokens/
https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

**Comment by GNSSYSTEMS-tg** [comment]
Hm, funny thing. I've based my work on [this](http://getblimp.github.io/django-rest-framework-jwt/#refresh-token), which for some reason follows a completely different philosophy. Since, obviously there is a discrepancy between the standard and my backend, how about providing a varied api? E.g. I could rename the option to `refreshAccessTokenUrl` or some other name.

**Comment by IsNull** [comment]
If I understand your design right, the only difference is that there is no special refresh_token and the access_token is (abused) for the refresh_token too. So it should be rather simple to support your special case but still be compatible with the standard by default:

By default, upon login the following JSON is expected:

```javascript
{
  token_type: "bearer"
  access_token: "my-jwt.token.asdf..."
  refresh_token: "abcdef..."
}
```

As the refresh token is opaque to our client, it does not care what its content is. So it might well be the access_token JWT. So if we allow to config the field names of the `access_token` and `refresh_token`, you could simply configure it as `refresh_token: "access_token"` so it will use the JWT for refreshing - if that is what your backend requires.

**Comment by IsNull** [comment]
I will give this a shot as it is something which we want to support in our system anyway. I merge this PR into a feature branch here and then refactor it to what I believe is compliant with the standard and still allows your use-case to work.

**Comment by GNSSYSTEMS-tg** [comment]
A version targeting more broad use cases is on its way...

**Comment by IsNull** [comment]
alright i will then wait until you have finished and will remerge into our feature branch.

**Comment by GNSSYSTEMS-tg** [comment]
I'm going to refactor a greater part of the code. Is it alright for you, if I just rename `Authentication*`to `Auth*`? This would make the code much more handy.

**Comment by IsNull** [comment]
Yes you can, as I already plan for some other breaking changes which will require a new major release anyway. Speaking of refactorings, I think it would be great to have the refresh handling in a separate class / file.  

The idea would be that the `TokenRefreshManager` would take a `refresh_token` and the use a configurable interval to refresh the current access_token. Once he gets the new access token, it will update it by invoking the AuthService. This way, the auth service does not increase in complexity too much.

**Comment by GNSSYSTEMS-tg** [comment]
Ok, I was planning a `TokenService` providing such a machanism. In my point of view, this would be more appropriate, since it'll combine all functionalities regarding tokens.

**Comment by IsNull** [comment]
Maybe you can go for a TokenService and a TokenRefreshService :) I guess you will see what plays out along the way.

**Comment by GNSSYSTEMS-tg** [comment]
Ok, I'm done for today. Would be great, if you have a look around the new code.

**Pull request merged**
