### PR TITLE
adds missing filter import for rxjs observables in AuthenticationService

### PR DESCRIPTION
**Pull request by GNSSYSTEMS-tg**

### CODE REVIEW

**Comment by IsNull** [comment]
Hey thanks for your PR I will have a look tomorrow and merge it.

**Comment by GNSSYSTEMS-tg** [comment]
Hi,

I'd love to see a new release with my changes soon. I'm planning to use your module in 2-3 projects right away. Additions may follow...

Cheers,
Tobi

**Comment by GNSSYSTEMS-tg** [comment]
Btw. testing aroung the services would be much appreciated!

**Comment by IsNull** [comment]
I certainly will release this tomorrow. The only thing I see that needs a bit discussion is the commented out logging. It helps enormously to find issues. I will research what the best practices are in TS for handling logging to allow to optionally disable it in prod builds.

As for the testing I completely agree. We just recently switched to TS and where not familiar with a lot of the moving parts, testing frameworks where one of them. I see what I can do as it is a very core library in our own products.

**Comment by GNSSYSTEMS-tg** [comment]
Point taken on the logging part. We've got this on another project, maybe I'll find a proper link for that matter.

As on the testing: sounds good, if the focus shifts onto this topic as well!

What kind of backend do you use? I just connected it to [django](https://github.com/GetBlimp/django-rest-framework-jwt) and it worked seamless. Thanks!

**Comment by IsNull** [comment]
As for the logging part we might shift to a logging library effectively supporting to filter on the log level. This is, at least in the Java world, the way to do it.  [ngx-logger](https://www.npmjs.com/package/ngx-logger) looks interesting.

> What kind of backend do you use? I just connected it to django and it worked seamless. Thanks!

We use mostly a Java [Spring Boot](https://projects.spring.io/spring-boot/) and [Spring Cloud](http://projects.spring.io/spring-cloud/) stack. However, as the JWT Token and OAuth part is well standardised it should not really matter.

**Comment by GNSSYSTEMS-tg** [comment]
I've included `ngx-logger`.

Btw about the support of standards: it's not common to find a framework or library doing the exact thing the standard requires. Sure, JWT is fairly easy to implement, but developers are lazy and do only the things they need to. In this case, your requirements match mine, luckily.

**Comment by GNSSYSTEMS-tg** [comment]
Another thing you might want to do besides testing: your code doesn't really follow a style guide (i.e. indents). It would be nice to have at least a tslint.json laying around.

**Comment by IsNull** [comment]
> your code doesn't really follow a style guide

That is surprising as since we enabled tslint, we had to basically change every 2nd line of code to make it happy :) So we actually put quite some effort into it. 

The intents could indeed be an issue - intellij can take over the tslint specified style however there might be some cases it wont handle intents right. What specific issues did you spot?

**ngx-logger**
About the ngx-logger integration, here it gets interesting. The `forRoot()` Module call is supposed to happen only once in an application (as it usually registers singleton services). See [forRoot Convention](http://angularfirst.com/the-ngmodule-forroot-convention/). The general rule is to not call `forRoot()` in a feature module. 

If a library wants to allow sub modules to import it, the convention is to have a forChild() module method. As this module does not offer this, we might either just import it normally (which will technically have no effect as it only has providers and they are in forRoot()). We could also rise an issue against their library, as I think a standard logging framework has to support feature libraries well.

I am personally not really happy with this design in angular, but thats what we got so far.

Btw, I very appreciate your valuable input and effort 👍

**Comment by GNSSYSTEMS-tg** [comment]
True, sorry for the howler. I've to admit, I haven't developed for a feature module, yet. Should be fixed now, plus another bug occurred in case there are no roles to work with.

How about a new release?

**Comment by GNSSYSTEMS-tg** [comment]
About the issues:
1. indents vary from 2 to 4 spaces (e.g. AuthGuardService has 2 spaces, most of the others have 4)
2. sorting of imports is inconsistent (usually first external dependencies, then your's)
3. formatting of imports is inconsistent (ES6 import/export braces)
4. formatting of line breaks within method signatures is not the way I'm used to in typescript

For IntelliJ users, these issues are _very_ easy to fix: Editor -> Code Style -> Typescript
- Tabs and Indents (1.)
- Spaces (3.)
- Imports (2.)
- Punctuation might be a helpful tab as well

**Comment by IsNull** [comment]
The setup of this library has two package json files. One in the root, used for the development, and one under src which is actually the one being uploaded to npm and used by clients.

As we have now introduced a required peer dependency, we should add the ngx-logger as such in [/src/package.json](https://github.com/ElderByte-/ngx-jwt-auth/blob/master/src/package.json). Also, you should reflect the updated rxjs library version in this package json.

Other than that I think we can merge. I will then increment the master version as this will introduce a breaking change (as all apps + libraries which use this library must now depend on ngx-logger and also import the module with forRoot)

**Comment by GNSSYSTEMS-tg** [comment]
> As we have now introduced a required peer dependency, we should add the ngx-logger as such in /src/package.json

Check. I've updated your `ngx-simple-webstorage` as well.

> Also, you should reflect the updated rxjs library version in this package json.

Did that in one of the previous commit.


In addition, the README.md should reflect a corresponding example for integrating `ngx-logger`.

**Pull request merged**
